version: "3.8" # 使用的 Docker Compose 文件版本

services:
  mysql:
    image: mysql:latest # 使用最新版本的 MySQL 镜像
    container_name: go-api # 指定容器名称
    restart: always # 使容器在退出时自动重启
    environment:
      MYSQL_ROOT_PASSWORD: mypassword # 设置 root 用户的密码
    ports:
      - "3306:3306" # 将容器的 3306 端口映射到主机的 3306 端口
    volumes:
      - mysql_data:/var/lib/mysql # 持久化 MySQL 数据

volumes:
  mysql_data: # 定义持久化数据卷
